var board = {
    "error": null,
    "total_board_count": 1912,
    "total_failed_board_count": 0,
    "total_target_board_count": 1251965,
    "labels": {
        "total_board_count": "Total",
        "total_failed_board_count": "Failed",
        "total_target_board_count": "Target",
        "board_count": "Board Count",
        "failed_board_count": "Failed",
        "target_board_count": "Target",
        "product_name": "Product",
        "setup_name": "Setup",
        "product_side": "Side",
        "module_count": "Panel Count",
        "placement_cycle_time": "Target Cycle",
        "takt_time": "TAKT Time"
    },
    "details": [
        {
            "name": "interval",
            "details": [
                {
                    "interval": "dec",
                    "product_name": "KBOTPRODA",
                    "setup_name": "LCRECIPE2",
                    "product_side": "B",
                    "board_count": 0,
                    "module_count": 0,
                    "placement_cycle_time": 0,
                    "takt_time": 0,
                    "target_board_count": 0,
                    "start_time": "2016-12-01 00:00:00",
                    "end_time": "2017-01-01 00:00:00",
                    "min_time": "2016-12-01 00:00:00"
                },
                {
                    "interval": "jan",
                    "product_name": "KBOTPRODA",
                    "setup_name": "LCRECIPE2",
                    "product_side": "B",
                    "board_count": 0,
                    "module_count": 0,
                    "placement_cycle_time": 0,
                    "takt_time": 0,
                    "target_board_count": 0,
                    "start_time": "2017-01-01 00:00:00",
                    "end_time": "2017-02-01 00:00:00",
                    "min_time": "2017-01-01 00:00:00"
                },
                {
                    "interval": "feb",
                    "product_name": "KBOTPRODA",
                    "setup_name": "LCRECIPE2",
                    "product_side": "B",
                    "board_count": 0,
                    "module_count": 0,
                    "placement_cycle_time": 0,
                    "takt_time": 0,
                    "target_board_count": 0,
                    "start_time": "2017-02-01 00:00:00",
                    "end_time": "2017-03-01 00:00:00",
                    "min_time": "2017-02-01 00:00:00"
                },
                {
                    "interval": "mar",
                    "product_name": "KBOTPRODA",
                    "setup_name": "LCRECIPE2",
                    "product_side": "B",
                    "board_count": 5,
                    "module_count": 15,
                    "placement_cycle_time": 2.395,
                    "takt_time": 34424.889,
                    "target_board_count": 0,
                    "start_time": "2017-03-01 00:00:00",
                    "end_time": "2017-04-01 00:00:00",
                    "min_time": "2017-03-03 12:21:18"
                },
                {
                    "interval": "mar",
                    "product_name": "KPRODUCTA",
                    "setup_name": "LCRECIPE2",
                    "product_side": "T",
                    "board_count": 1831,
                    "module_count": 1831,
                    "placement_cycle_time": 2.072,
                    "takt_time": 124.939,
                    "target_board_count": 0,
                    "start_time": "2017-03-01 00:00:00",
                    "end_time": "2017-04-01 00:00:00",
                    "min_time": "2017-03-03 12:21:18"
                },
                {
                    "interval": "mar",
                    "product_name": null,
                    "setup_name": null,
                    "product_side": null,
                    "board_count": 0,
                    "module_count": 0,
                    "placement_cycle_time": 0,
                    "takt_time": 0,
                    "target_board_count": 0,
                    "start_time": "2017-03-01 00:00:00",
                    "end_time": "2017-04-01 00:00:00",
                    "min_time": "2017-03-30 08:21:15"
                },
                {
                    "interval": "apr",
                    "product_name": "KPRODUCTA",
                    "setup_name": "LCRECIPE2",
                    "product_side": "T",
                    "board_count": 40,
                    "module_count": 40,
                    "placement_cycle_time": 2.072,
                    "takt_time": 124.939,
                    "target_board_count": 112819,
                    "start_time": "2017-04-01 00:00:00",
                    "end_time": "2017-05-01 00:00:00",
                    "min_time": "2017-04-01 00:00:25"
                },
                {
                    "interval": "apr",
                    "product_name": "KPRODUCTA",
                    "setup_name": "LCRECIPE2",
                    "product_side": "T",
                    "board_count": 40,
                    "module_count": 40,
                    "placement_cycle_time": 2.072,
                    "takt_time": 124.939,
                    "target_board_count": 572,
                    "start_time": "2017-04-01 00:00:00",
                    "end_time": "2017-05-01 00:00:00",
                    "min_time": "2017-04-01 00:00:25"
                },
                {
                    "interval": "apr",
                    "product_name": null,
                    "setup_name": null,
                    "product_side": null,
                    "board_count": 0,
                    "module_count": 0,
                    "placement_cycle_time": 0,
                    "takt_time": 0,
                    "target_board_count": 0,
                    "start_time": "2017-04-01 00:00:00",
                    "end_time": "2017-05-01 00:00:00",
                    "min_time": "2017-04-04 13:11:11"
                },
                {
                    "interval": "apr",
                    "product_name": "KPRODUCTA",
                    "setup_name": "IndepentRecipe",
                    "product_side": "B",
                    "board_count": 0,
                    "module_count": 0,
                    "placement_cycle_time": 2.593,
                    "takt_time": 0,
                    "target_board_count": 0,
                    "start_time": "2017-04-01 00:00:00",
                    "end_time": "2017-05-01 00:00:00",
                    "min_time": "2017-04-04 13:12:12"
                },
                {
                    "interval": "apr",
                    "product_name": "KPRODUCTA",
                    "setup_name": "IndepentRecipe",
                    "product_side": "B",
                    "board_count": 0,
                    "module_count": 0,
                    "placement_cycle_time": 4.394,
                    "takt_time": 0,
                    "target_board_count": 0,
                    "start_time": "2017-04-01 00:00:00",
                    "end_time": "2017-05-01 00:00:00",
                    "min_time": "2017-04-04 13:39:36"
                },
                {
                    "interval": "apr",
                    "product_name": "KBOTPRODA",
                    "setup_name": "LCRECIPE2",
                    "product_side": "B",
                    "board_count": 13,
                    "module_count": 39,
                    "placement_cycle_time": 2.395,
                    "takt_time": 34424.889,
                    "target_board_count": 258726,
                    "start_time": "2017-04-01 00:00:00",
                    "end_time": "2017-05-01 00:00:00",
                    "min_time": "2017-04-04 13:47:11"
                },
                {
                    "interval": "apr",
                    "product_name": "KPRODUCTA",
                    "setup_name": "LCRECIPE2",
                    "product_side": "T",
                    "board_count": 0,
                    "module_count": 0,
                    "placement_cycle_time": 3.401,
                    "takt_time": 130187.435,
                    "target_board_count": 572,
                    "start_time": "2017-04-01 00:00:00",
                    "end_time": "2017-05-01 00:00:00",
                    "min_time": "2017-04-28 11:05:21"
                },
                {
                    "interval": "apr",
                    "product_name": "KPRODUCTA",
                    "setup_name": "LCRECIPE2",
                    "product_side": "T",
                    "board_count": 0,
                    "module_count": 0,
                    "placement_cycle_time": 3.401,
                    "takt_time": 130187.435,
                    "target_board_count": 112819,
                    "start_time": "2017-04-01 00:00:00",
                    "end_time": "2017-05-01 00:00:00",
                    "min_time": "2017-04-28 11:05:21"
                },
                {
                    "interval": "may",
                    "product_name": null,
                    "setup_name": null,
                    "product_side": null,
                    "board_count": 0,
                    "module_count": 0,
                    "placement_cycle_time": 0,
                    "takt_time": 0,
                    "target_board_count": 0,
                    "start_time": "2017-05-01 00:00:00",
                    "end_time": "2017-06-01 00:00:00",
                    "min_time": "2017-05-01 00:00:58"
                },
                {
                    "interval": "may",
                    "product_name": "KPRODUCTA",
                    "setup_name": "LCRECIPE2",
                    "product_side": "T",
                    "board_count": 20,
                    "module_count": 20,
                    "placement_cycle_time": 3.401,
                    "takt_time": 130187.435,
                    "target_board_count": 741827,
                    "start_time": "2017-05-01 00:00:00",
                    "end_time": "2017-06-01 00:00:00",
                    "min_time": "2017-05-02 15:11:13"
                },
                {
                    "interval": "jun",
                    "product_name": "KPRODUCTA",
                    "setup_name": "LCRECIPE2",
                    "product_side": "T",
                    "board_count": 3,
                    "module_count": 3,
                    "placement_cycle_time": 3.401,
                    "takt_time": 130187.435,
                    "target_board_count": 138022,
                    "start_time": "2017-06-01 00:00:00",
                    "end_time": "2017-07-01 00:00:00",
                    "min_time": "2017-06-01 08:21:55"
                }
            ],
            "label": "Month",
            "board_ratio_key": "may",
            "board_count": 20,
            "failed_board_count": 0,
            "target_board_count": 741827,
            "board_ratio": 0
        },
        {
            "name": "shift_name",
            "details": null,
            "label": "Shift",
            "board_ratio_key": "shift1",
            "board_count": 9,
            "failed_board_count": 0,
            "target_board_count": 422258,
            "board_ratio": 0
        },
        {
            "name": "product_name",
            "details": [
                {
                    "product_name": "KBOTPRODA",
                    "setup_name": "LCRECIPE2",
                    "product_side": "B",
                    "board_count": 18,
                    "module_count": 54,
                    "placement_cycle_time": 2.395,
                    "takt_time": 34424.889
                },
                {
                    "product_name": "KPRODUCTA",
                    "setup_name": "IndepentRecipe",
                    "product_side": "B",
                    "board_count": 0,
                    "module_count": 0,
                    "placement_cycle_time": 2.593,
                    "takt_time": 0
                },
                {
                    "product_name": "KPRODUCTA",
                    "setup_name": "IndepentRecipe",
                    "product_side": "B",
                    "board_count": 0,
                    "module_count": 0,
                    "placement_cycle_time": 4.394,
                    "takt_time": 0
                },
                {
                    "product_name": "KPRODUCTA",
                    "setup_name": "LCRECIPE2",
                    "product_side": "T",
                    "board_count": 1871,
                    "module_count": 1871,
                    "placement_cycle_time": 2.072,
                    "takt_time": 124.939
                },
                {
                    "product_name": "KPRODUCTA",
                    "setup_name": "LCRECIPE2",
                    "product_side": "T",
                    "board_count": 23,
                    "module_count": 23,
                    "placement_cycle_time": 3.401,
                    "takt_time": 130187.435
                },
                {
                    "product_name": null,
                    "setup_name": null,
                    "product_side": null,
                    "board_count": 0,
                    "module_count": 0,
                    "placement_cycle_time": 0,
                    "takt_time": 0
                }
            ],
            "label": "Product",
            "board_ratio_key": "KBOTPRODA",
            "board_count": 18,
            "failed_board_count": 0,
            "target_board_count": 258726,
            "board_ratio": 0.01
        },
        {
            "name": "equipment_name",
            "details": null,
            "label": "Equipment",
            "board_ratio_key": "NPM-D",
            "board_count": 1912,
            "failed_board_count": 0,
            "target_board_count": 1251965,
            "board_ratio": 0.15
        },
        {
            "name": "lane_no",
            "details": null,
            "label": "Lane",
            "board_ratio_key": "1",
            "board_count": 1907,
            "failed_board_count": 0,
            "target_board_count": 1251965,
            "board_ratio": 0.15
        },
        {
            "name": "route_name",
            "details": null,
            "label": "Route",
            "board_ratio_key": "LCLine-2",
            "board_count": 1912,
            "failed_board_count": 0,
            "target_board_count": 1251965,
            "board_ratio": 0.15
        },
        {
            "name": "interval_pmd",
            "details": [
                {
                    "interval": "mar",
                    "board_count": 1836,
                    "module_count": 1846,
                    "sum_board_count": 1836,
                    "sum_module_count": 1846,
                    "start_time": "2017-03-01 00:00:00",
                    "end_time": "2017-04-01 00:00:00"
                },
                {
                    "interval": "apr",
                    "board_count": 53,
                    "module_count": 79,
                    "sum_board_count": 1889,
                    "sum_module_count": 1925,
                    "start_time": "2017-04-01 00:00:00",
                    "end_time": "2017-05-01 00:00:00"
                },
                {
                    "interval": "may",
                    "board_count": 20,
                    "module_count": 20,
                    "sum_board_count": 1909,
                    "sum_module_count": 1945,
                    "start_time": "2017-05-01 00:00:00",
                    "end_time": "2017-06-01 00:00:00"
                },
                {
                    "interval": "jun",
                    "board_count": 3,
                    "module_count": 3,
                    "sum_board_count": 1912,
                    "sum_module_count": 1948,
                    "start_time": "2017-06-01 00:00:00",
                    "end_time": "2017-07-01 00:00:00"
                }
            ],
            "label": "Month",
            "board_ratio_key": null,
            "board_count": 20,
            "failed_board_count": null,
            "target_board_count": null,
            "board_ratio": null
        }
    ],
    "source": "usp_get_pa_board_count",
    "parameters": {
        "start_time": "2016-12-6 0:0:0",
        "end_time": "2017-06-06 10:23:32"
    },
    "call_time": "2017-06-06 08:23:47",
    "execution_time": "00:00:20.891116"
}